security:
  oauth2:
    client:
      clientId: 547424193396-si6c8p8gsbm5g4ieav78i9tous9hboi4.apps.googleusercontent.com
      clientSecret: W2edb4xkAMUx-_Ym5_hpn3IH
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true